// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tirzjivmgyzqshlzyfau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcnpqaXZtZ3l6cXNobHp5ZmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0MjM4MDQsImV4cCI6MjA4NTk5OTgwNH0.giy1h0k5ZDpj8-W8pycLEbztzyYE8CEW_H1DjSHsBvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});